# base getails
title:        Adopta Agency Blueprint
url:          http://blueprint.adopta.agency

#versioning is good with each iteration
version:      1.1.1

#who is in charge of this show
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
  twitter:    'kinlane'
  github:     'kinlane'

#some configurations for the site
markdown:     rdiscount
permalink:    pretty
pygments:     true

# some blog settings
permalink: /:categories/:year/:month/:day/:title
paginate: 25
paginate_path: "/blog/page:num"

#what files should be excluded
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

collections:
  - datastores:
    output: true
    - title: "Table 1.1 - Summary of Receipts, Outlays, and Surpluses or Deficits 1789 through 2020"
    - title: "Table 1.2 - Summary of Receipts, Outlays, and Surpluses or Deficits as Percentages of GDP 1930–2020"
    - title: "Table 1.3  - Summary of Receipts, Outlays, and Surpluses or Deficits in Current Dollars, Constant Dollars, and as Percentages of GDP 1940–2020"    
