# ------------------------
# Adopta Agency Blueprint
# This is meant to be a blueprint for opening up data.
# You control everything about this site, here in the _config.yml
# All data is stored under /data
# All API definitions are stored under /api
# Tell your story via the Blog
# Manage all conversations through Github issues
# ------------------------

# Project details
project_title: Adopta Blueprint
project_description: This is the master blueprint for the Adopta.Agency.
project_url: http://adopta-agency.github.io/adopta-blueprint/

github_user: adopta-agency
github_repo: adopta-blueprint

# ---------
# Data
# ---------
data_show: yes
data_nav: yes
data_title: Data Files
data_description: This is a list of JSON and CSV conversions of the Excel files made avalable as part of the <a href="https://www.whitehouse.gov/omb/budget/Historicals">Office of Management and Budget Historical Tables</a>, providing data on budget receipts, outlays, surpluses or deficits, Federal debt, and Federal employment over an extended time period, generally from 1940 or earlier to 2016 or 2020.
data_footer: The goal of publishing these CSV and JSON alternatives is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

data:
  - title: "Table 1.1 - Summary of Receipts, Outlays, and Surpluses or Deficits 1789 through 2020"
    csv_url: "https://kinlane.github.io/us-federal-budget/data/federal-budget-table-1-1.csv"
    json_url: "https://kinlane.github.io/us-federal-budget/data/federal-budget-table-1-1.json"
  - title: "Table 1.2 - Summary of Receipts, Outlays, and Surpluses or Deficits as Percentages of GDP 1930–2020"
    csv_url: "https://kinlane.github.io/us-federal-budget/data/federal-budget-table-1-2.csv"
    json_url: "https://kinlane.github.io/us-federal-budget/data/federal-budget-table-1-2.json"

# ---------
# APIs
# ---------

api_show: no
api_nav: yes
api_title: APIs
api_description: This is a list of APIs generated from the Excel files made avalable as part of the <a href="https://www.whitehouse.gov/omb/budget/Historicals">Office of Management and Budget Historical Tables</a>, providing data on budget receipts, outlays, surpluses or deficits, Federal debt, and Federal employment over an extended time period, generally from 1940 or earlier to 2016 or 2020.
api_footer: The goal of launching these APIs is to make this data easier to consumer, and integrate into websites, applications, visualizations, and other integrations.

api:
  - title: Table 1
    swagger_url: https://kinlane.github.io/us-federal-budget/api/federal-budget-table-1.json
  - title: Table 2
    swagger_url: https://kinlane.github.io/us-federal-budget/api/federal-budget-table-2.json

# ---------
# Showcase
# ---------

showcase_show: yes
showcase_nav: no
showcase_title: Showcase
showcase_description: These are some of the things being build on top of this open data and APIs.
showcase_footer: This project is designed to be used, and extended, please share what you have built so it can be included.

showcase:
  - title: Showcase Item One
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com
  - title: Showcase Item Two
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com
  - title: Showcase Item Four
    description: This is the description for the first thing that was build on top of the data or APIs included as part of this project.
    image: https://s3.amazonaws.com/kinlane-productions/api-commons/api-commons-icon.png
    url: http://apievangelist.com

# ---------
# FAQ
# ---------

faq_show: yes
faq_nav: no
faq_title: FAQ
faq_description: These are some of the common questions that need answering or get asked as part of this work.
faq_footer: Questions that get submitted via the projects Github issue managment are sometimes added here.

faq:
  - question: Why are you doing this?
    answer: I want to make the data around the US federal budget more accessible and usable, encouraging people to build it into more websites, applications, visualizations, and anywhere it can be used.
  - question: Where did this data come from?
    answer: It is from the <a href="https://www.whitehouse.gov/omb/budget/Historicals">Office of Management and Budget Historical Tables</a>.
  - question: What are you planning on doing with this data?
    answer: You can visit the <a href="https://kinlane.github.io/us-federal-budget/roadmap/">roadmap for more information.
  - question: How do I talk to someone behind this project?
    answer: This site runs on Github Pages, and relies on Github issue management for support. <a href="https://github.com/kinlane/us-federal-budget/issues/new">Go ahead and submit an issue</a> via the project repository.

# ---------
# Team
# ---------

team_show: yes
team_nav: no
team_title: Team
team_description: This is a solo project conducted by Kin Lane as part of the Adopta.Agency project.
team_footer: If you would like to get involved with this work, please submit an issue via the Github repo.

team:
  - name: Kin Lane
    description: The API Evangelist, working to make data, content, and other digital resources more accessible.
    url: http://kinlane.com

# ---------
# Tools
# ---------

tools_show: yes
tools_nav: no
tools_title: Tools
tools_description: This is a list of tools that are used as part of this project.
tools_footer: We share the tools we used to help others understand how to recreate the work.

tools:
  - title: Github
    description: A social network built around software development platform Git.
    url: http://github.com
  - title: Github Pages
    description: Websites for projects that are hosted directly from a GitHub repository.
    url: https://pages.github.com/
  - title: Google Spreadsheets
    description: Cloud-based spreadsheets as part of the overall Google Dirve platform.
    url: https://www.google.com/drive/
  - title: API Spark
    description: A platform for the creation, hosting, management, and consumption of web APIs.
    url: http://restlet.com/products/apispark/
  - title: CSV Converter
    description: A CSV conversion tool that runs on Github, created from Mr. Data Converter.
    url: http://kinlane.github.io/csv-converter/

# ---------
# Blog
# ---------

permalink: /:categories/:year/:month/:day/:title
paginate: 25
paginate_path: "/blog/page:num"
blog_nav: yes

# ---------
# Support
# ---------

# URL to the issues page for this
support_title: Support
support_description: If you need any help, have questions, or would like to get involved, please use the following links.
support_twitter: kinlane

# ---------
# Roadmap
# ---------

roadmap_nav: yes

# ---------
# Change Log
# ---------

changelog_nav: yes

# ---------
# General Settings
# ---------

#versioning your peojct is good
version:      1.1.1

#some configurations for the site
markdown:     rdiscount
permalink:    pretty
pygments:     true


#what files should be excluded
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
