# base getails
title:        Adopta Agency Blueprint
url:          http://blueprint.adopta.agency

#versioning is good with each iteration
version:      1.1.1

#who is in charge of this show
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
  twitter:    'kinlane'
  github:     'kinlane'

#some configurations for the site
markdown:     rdiscount
permalink:    pretty
pygments:     true

# some blog settings
permalink: /:categories/:year/:month/:day/:title
paginate: 25
paginate_path: "/blog/page:num"

#what files should be excluded
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

collections:
- data
